# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  blazorserver1:
    image: blazorserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "5001:5000"
      
  blazorserver2:
    image: blazorserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "5002:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blazorserver1
      - blazorserver2
    ports:
      - "4000:4000"